### ISSUE TITLE
shp-index needs a new node-mapnik tag

### ISSUE THREAD

**Issue by rclark** [mapbox/preprocessorcerer#1]
The preprocessor that creates a spatial index on shapefiles should start to work once there's a new release of node-mapnik that includes https://github.com/mapnik/node-mapnik/pull/379.

@springmeyer curious if you have a timeline/plan for node-mapnik releases?

**Comment by springmeyer** [comment]
@rclark working with @flippmoke on a new tag today. We're honing https://github.com/mapnik/node-mapnik/blob/master/docs/Contributing.md as we go. Watch for when this milestone is closed: https://github.com/mapnik/node-mapnik/milestones/v3.1.5.

**Comment by springmeyer** [comment]
Now planning to hit this by tuesday.

**Comment by springmeyer** [comment]
Now done, node-mapnik v3.1.5 is out.
