### ISSUE TITLE
Drop buildOverviews temporarily

### ISSUE THREAD

**Issue by rclark** [mapbox/preprocessorcerer#24]
We've noticed bad overviews coming through the preprocessorcerer, resulting in yellow patches on imagery.

Dropping the preprocessor for now, and taking this up as a bug in node-gdal.

**Comment by rclark** [comment]
https://github.com/naturalatlas/node-gdal/issues/93

**Comment by rclark** [comment]
Turns out the answer is as simple as calling `ds.close()` after building overviews. This ensures that everything is written to the file before garbage collection throws out the datasource object.

I'll work on a test case and deploy a fix.

**Comment by springmeyer** [comment]
The overview generator is not stable per https://github.com/mapbox/preprocessorcerer/issues/49#issuecomment-157136060. Let's revisit re-enabling once node-gdal no longer crashes
