### ISSUE TITLE
jscs --> eslint

### ISSUE THREAD

**Issue by GretaCB** [mapbox/preprocessorcerer#27]
Due to randomly changing Airbnb js style standards...switch to using a separate [`.eslintrc` file](https://github.com/mapbox/earcut/blob/master/.eslintrc), suggestion by @mourner 

cc @rclark

**Comment by rclark** [comment]
Another option would be to pin the jscs version in package.json.

**Comment by hzoo** [comment]
You can also copy all the rules from the preset into your config.
