### ISSUE TITLE
Remove extraneous mbtiles records

### ISSUE THREAD

**Issue by rclark** [mapbox/preprocessorcerer#32]
As part of preprocessing, we should:

```
DELETE from map where tile_id is null
```

... followed by vacuum on the database.

@BergWerkGIS let me know if you have time to take this on, otherwise I'll tackle it.

**Comment by BergWerkGIS** [comment]
@rclark I'm deep into the sprint this week. Would be great if you could tackle it.

Should even work as a one liner:
```
DELETE from map where tile_id is null; VACUUM;
```
Let me know if you need anything else.
