### ISSUE TITLE
Generate indexes for CSV and GeoJSON files

### ISSUE THREAD

**Issue by springmeyer** [mapbox/preprocessorcerer#43]
Latest node-mapnik [supports the `mapnik-index` command](https://github.com/mapnik/node-mapnik/commit/c2a236ec05b9a97a6aa52515974f52b0b30a6861) for indexing CSV and GeoJSON files.

We now need a pre-processing step, like [shp-index](https://github.com/mapbox/preprocessorcerer/blob/master/preprocessors/shp-index.preprocessor.js) to do this for `geojson` and `csv` files. One consideration is that these files might have a variety of extentions like `json` or  `geojson` for GeoJSON and `.tsv`, `txt`, `csv`, etc for CSV.

**Comment by rclark** [comment]
File extensions shouldn't be too big a deal -- we have have mapbox-file-sniff detecting filetypes already.

**Comment by GretaCB** [comment]
Next action:
- [ ] enforce a file extension, since `mapnik-index` requires an extension. Otherwise it will silently not index.

**Comment by GretaCB** [comment]
Done and deployed.
