### ISSUE TITLE
How disabled processors should work / getting code coverage working

### ISSUE THREAD

**Issue by springmeyer** [mapbox/preprocessorcerer#49]
https://github.com/mapbox/preprocessorcerer/commit/176d67b82c0cce84ef7b7aff80624ca22e781435 added preliminary code coverage support with the aim of helping us get to 100% coverage.

But coverage is not yet getting posted because it breaks. Creating this ticket until I fix. The problem is that the `disabled` tests are run and they are in a broken state because:

  - 1) their requires are broken
  - 2) one expected result was out of date due to #47
  - 3) the overviews test, once enabled, crashes: https://travis-ci.org/mapbox/preprocessorcerer/jobs/89258924

1) and 2) were fixed in https://github.com/mapbox/preprocessorcerer/commit/7314b3f803fd253b4622f231e734fc2a218e4e31 and https://github.com/mapbox/preprocessorcerer/commit/66832e5c027b9079dbc3168ef5a0b90f9aefa2e7.

TODO:

  - Either fix 3); or;
  - Make it so that the disabled tests do not run and therefore do not help provide code coverage.

/cc @rclark for spiritual guidance. I'm setting up coverage to aim at 100%. Do we want to keep testing disabled processors so they do not drift towards brokenness?

**Comment by rclark** [comment]
I say drop the disabled preprocessors. They're relatively simple node-gdal scripts if we ever decide to resurrect them.

**Comment by springmeyer** [comment]
> I say drop the disabled preprocessors

:+1: I'll do that in a pull request shortly. Thanks.

**Comment by springmeyer** [comment]
note: my assumption is that the overview generator was disabled because it was not stable. I've filed https://github.com/naturalatlas/node-gdal/issues/137 to track getting it more stable in the hopes we might be able to re-enable it in the future.
