### ISSUE TITLE
Implement --index-parts for shapefiles

### ISSUE THREAD

**Issue by GretaCB** [mapbox/preprocessorcerer#58]
Add [Mapnik's `--index-parts` flag](https://github.com/mapnik/mapnik/pull/3217/files) for all shapefile preprocessing.

To quote @BergWerkGIS 's comments:

It's useful:
* if there are any multipart features at all
* the multipart features have a big bounding box, but also contain small features

`--index-parts` should help if there are multipart features like this:

```
 ______________________________
|   _       _   _              |
|  |_|   _ |_| |_|             |
|       |_|                    |
|                              |
|             _                |
|      _     |_|               |
|     |_|                      |
|                              |
|                _   _         |
|               |_| |_|        |
|     _             _          |
|    |_|           |_|         |
|                              |
|______________________________|

```

And to quote @springmeyer 's comments:
> My understanding is that `--index-parts` is fine to use in all cases. No major slowdowns on non-multipart features are anticipated, but speedups for multipart features should be seen.

**Comment by mapsam** [comment]
@GretaCB looks like this can be closed since https://github.com/mapbox/preprocessorcerer/pull/59/files is merged?

**Comment by GretaCB** [comment]
👍  totes, thank you! Closing.
