### ISSUE TITLE
expected errors from mapnik-index not always present when run from mapnik-swoop

### ISSUE THREAD

**Issue by mapsam** [mapbox/preprocessorcerer#62]
Running through mapnik-swoop updates today and seeing failures from preprocessorcerer, but when running tests in preprocessorcerer directly we do not see the failures.

```
preprocessorcerer --> 
waiting...
not ok 107 error properly handled
  ---
    operator: ok
    expected: true
    actual:   undefined
    at: ChildProcess.<anonymous> (/home/travis/build/mapbox/mapnik-swoop/node_modules/preprocessorcerer/preprocessors/spatial-index.preprocessor.js:39:16)
  ...
not ok 108 expected error message
  ---
    operator: equal
    expected: 'Invalid geojson feature'
    actual:   undefined
    at: ChildProcess.<anonymous> (/home/travis/build/mapbox/mapnik-swoop/node_modules/preprocessorcerer/preprocessors/spatial-index.preprocessor.js:39:16)
  ...
waiting...
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

This seems related to expecting `stderr` to print properly, which gets mucky when running from another repository. Looks like [this has been an issue in the past](https://github.com/mapbox/preprocessorcerer/commit/291c55058996e3d130f822072901ff53d7ba76e3), and is probably worth revisiting.

cc @springmeyer @GretaCB

**Comment by springmeyer** [comment]
one more data point: saw a mapnik-swoop linux travis jobs hit this again when running node v0.10. But the node v4 version did not.

**Comment by springmeyer** [comment]
Looks pretty variable. Now hit a mapnik-swoop run where node v0.10 passed by node v4 hit this problem: https://travis-ci.org/mapbox/mapnik-swoop/builds/123975663

**Comment by GretaCB** [comment]
This keeps sneaking back. It comes and goes randomly on Travis, but cant replicate locally. @BergWerkGIS and I had discussed exposing `data` within the returned error message, but then realized it exposed filepaths that bring up security concerns. I can try rerunning Travis on a non-deployed branch with `data` exposed in the message to try and determine the exact error.

**Comment by GretaCB** [comment]
Update: Per chat with @BergWerkGIS and @springmeyer , node-mapnik will still send `EXIT_SUCCESS` if invalid features. Plan is to have node-mapnik return an `error code > 0` so that it can be translated as a full error. @BergWerkGIS is currently working on next steps.

**Comment by BergWerkGIS** [comment]
Changed test here: https://github.com/mapbox/preprocessorcerer/compare/togeojson...mapnik-index-test
Did it already yesterday, so it's branched off `togeojson`.

**Comment by springmeyer** [comment]
@BergWerkGIS Next mapnik release is targeted next Monday. Please create a ticket/pull for anything that needs fixed upstream in Mapnik core ASAP.

**Comment by artemp** [comment]
@mapsam - https://github.com/mapnik/mapnik/commit/1871e5f62d8bd311e1ecf0a9ae996beb2ef5022c fixes this issue by returning EXIT_FAILURE on invalid input. Using latest `mapnik-index` and https://github.com/mapbox/preprocessorcerer/tree/mapnik-index-test all tests are passing for me.

So next steps are looking like:

- [ ] -  mapnik SDK linux binaries
- [ ] -  node-mapnik dev build that points to ^ new SDK
- [ ] -  pre-processor build against ^ new node-mapnik and confirm all tests are passing 

@mapsam ^ could you fire up the above and let me know if any problems, I'll check in first thing tomorrow morning my time, cheers!

/cc @springmeyer @GretaCB @BergWerkGIS

**Comment by mapsam** [comment]
Built the Mapnik linux binaries based off the most recent commit to `master` - gitsha `4b3b62a40ceb886f0f8fe686a83d17d3de7d19a3`

mapnik-binaries: s3://mapnik/dist/dev/mapnik-linux-sdk-4b3b62a40ceb886f0f8fe686a83d17d3de7d19a3.tar.bz2
node-mapnik build: https://mapnik-slugs.s3.amazonaws.com/node-mapnik-4b3b62a40ceb886f0f8fe686a83d17d3de7d19a3.tar.gz

Going to stage a pre-processorcer against this node-mapnik binary and see what happens.

cc @artemp @springmeyer @GretaCB @BergWerkGIS

**Comment by mapsam** [comment]
The `stderr-fix` branch is up and running. Pointing mapnik-swoop at this branch and testing.

**Comment by mapsam** [comment]
@artemp @BergWerkGIS we have a successfully built node-mapnik binary (linux, node `0.10`) that is passing on Travis! https://travis-ci.org/mapbox/preprocessorcerer/builds/126734867

Mapnik swoop looks great as well. https://travis-ci.org/mapbox/mapnik-swoop/builds/126735029

**Keep in mind** that the dev Node Mapnik build only works for a single architecture/node version so the other failing jobs (osx, nodev4) are failing as expected. Once we get a node-mapnik published we can retest and expect these to pass, then merge in the fix.

cc @GretaCB @springmeyer

**Comment by mapsam** [comment]
The updates in mapbox/unpacker#1232 should solve this issue!

**Comment by mapsam** [comment]
Tagging party has completed. Whammo!
