### ISSUE TITLE
KML too many layers not tested fully

### ISSUE THREAD

**Issue by mapsam** [mapbox/preprocessorcerer#67]
Currently when uploading the ["too many layers" KML](https://github.com/mapbox/preprocessorcerer/blob/master/test/fixtures/kml/fail-more-than-15-layers.kml) fixture to mapbox.com/studio it results in the following error:

```
OGR file contains no features. If KML, NetworkLinks are not supported
```

I'd expect it to be:

```
X layers found. Maximum of 15 layers allowed.
```

Will work on putting together a valid test fixture and updating!

cc @BergWerkGIS @GretaCB

**Comment by mapsam** [comment]
![screen shot 2016-07-07 at 12 01 26 pm](https://cloud.githubusercontent.com/assets/1943001/16667003/03ebd250-443f-11e6-8686-ee375a950740.png)

New feature with real geometry fails as expected. Not sure why this isn't being caught with the original text fixture.

**Comment by mapsam** [comment]
Things look fine in preprocessorceror - going to close this.

**Comment by GretaCB** [comment]
🙌
