### ISSUE TITLE
shp reproject is listed in readme but not enabled

### ISSUE THREAD

**Issue by tmcw** [mapbox/preprocessorcerer#70]
ee0cbd7c9bf0ae0bf4f8b9a9ff8e209782e865c8 removed the shp-reproject step due to #34 , but we list it under [Potential Preprocessory](https://github.com/mapbox/preprocessorcerer#potential-preprocessorcery).

@rclark if Shapefiles aren't reprojected here, are they reprojected at some other stage?

**Comment by rclark** [comment]
Not explicitly -- mapnik accepts shapefiles in any projection and reprojects data while cutting tiles. 

The potential preprocessorcery should no longer list this.
